### ISSUE TITLE
Bug: Latest update made the icons much bigger

### ISSUE THREAD

**Issue by DaveB1977** [SFX-WoW/Masque_Apathy#10]
**Game Version**
9.01 pre-patch

**Add-On Version**
Was fine with version 9.0.0 but not with 9.0.1

**Describe the Issue**
It's hard to describe, but the update makes the addons more... swollen?

![before](https://user-images.githubusercontent.com/52803773/97174713-5e4d9300-178a-11eb-936b-e8b9d97f200c.jpg)
![after](https://user-images.githubusercontent.com/52803773/97174715-5f7ec000-178a-11eb-9c1c-87d0cdea97ff.jpg)

**Comment by StormFX** [comment]
This isn't a bug, though it seems I did forget to add it to the change log. The overall size of the button was increased by 4 pixels (2 on each side).

**Comment by DaveB1977** [comment]
Nooooooooooooooooo, is there any way to "unfix" it, as my OCD UI depended on the seperation provided by this skin :( As there are multplie components affected, some of which do not allow scaling and/or padding, i've had no choice but to roll-back to the "working" version :(

**Comment by StormFX** [comment]
I'll look into it. I did it primarily to skirt any potential issues with the increase in texture resolution.
